# Generated by Django 4.2.7 on 2023-11-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggotatiminjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=191)),
                ('email', models.CharField(max_length=191)),
                ('nim', models.CharField(max_length=191)),
                ('nomor_telepon', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'AnggotaTimInjection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fotografi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_bukti_pembayaran', models.CharField(max_length=191)),
                ('email', models.CharField(max_length=191)),
                ('nama_lengkap', models.CharField(max_length=191)),
                ('nomor_telepon', models.CharField(max_length=191)),
                ('asal_sekolah', models.CharField(max_length=191)),
                ('deskripsi_karya', models.CharField(max_length=191)),
                ('domisili', models.CharField(max_length=191)),
                ('judul_karya', models.CharField(max_length=191)),
                ('link_bukti_follow', models.CharField(max_length=191)),
                ('link_dokumen_keaslian', models.CharField(max_length=191)),
                ('link_foto_karya', models.CharField(max_length=191)),
                ('link_post_instagram', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'Fotografi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tim', models.CharField(max_length=191, unique=True)),
                ('asal_sekolah', models.CharField(max_length=191)),
                ('nama_pembimbing', models.CharField(max_length=191)),
                ('no_telp_pembimbing', models.CharField(max_length=191)),
                ('link_berkas_bukti', models.CharField(max_length=191)),
                ('link_berkas_abstrak', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'Injection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrismaMigrations',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=64)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('migration_name', models.CharField(max_length=255)),
                ('logs', models.TextField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('applied_steps_count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': '_prisma_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, unique=True)),
            ],
            options={
                'db_table': 'TeamType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=191, unique=True)),
                ('namalengkap', models.CharField(blank=True, max_length=191, null=True)),
                ('password', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'Verifikasi',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
